name: Deploy Angular

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci
      - run: npm run build

      - name: Check dist folder
        run: |
          ls -la dist
          ls -la dist/ionita-tech
          ls -la dist/ionita-tech/browser

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Deploy with FTP
        run: |
          lftp -d -u "${{ secrets.FTP_USERNAME }}","${{ secrets.FTP_PASSWORD }}" "${{ secrets.FTP_HOST }}" <<EOF
          set ftp:ssl-allow no
          set ftp:passive-mode on
          set net:timeout 60
          set net:max-retries 3
          set net:reconnect-interval-base 5

          mirror -R --delete --verbose ./dist/ionita-tech/browser/ public_html/

          bye
          EOF
