name: Deploy Angular

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - run: npm run build

      - name: Check build output
        run: |
          pwd
          ls -la
          ls -la dist
          ls -la dist/ionita-tech
          ls -la dist/ionita-tech/browser

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Deploy with FTP
        run: |
          lftp -u "${{ secrets.FTP_USERNAME }}","${{ secrets.FTP_PASSWORD }}" ${{ secrets.FTP_HOST }} <<EOF
          set ftp:ssl-allow no
          set net:timeout 30
          set net:max-retries 2
          pwd
          ls
          cd public_html
          pwd
          mirror -R --delete --verbose ./dist/ionita-tech/browser/ .
          bye
          EOF
