name: Deploy Angular

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci
      - run: npm run build

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Deploy with FTP
        run: |
          lftp -u "${{ secrets.FTP_USERNAME }}","${{ secrets.FTP_PASSWORD }}" ${{ secrets.FTP_HOST }} <<EOF
          set ftp:ssl-allow no
          set net:timeout 30
          set net:max-retries 2

          mkdir -p public_html
          cd public_html

          mirror -R --verbose ./dist/ionita-tech/browser/ .

          bye
          EOF
